spring.application.name=my-java-web
server.port=8080
spring.thymeleaf.cache=false
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms
logging.level.org.springframework.web=DEBUG